Controllers/MST_BranchController.cs
using Microsoft.AspNetCore.Mvc;
using StudentMaster.Models;
using System.Data.SqlClient;
using System.Data;

namespace StudentMaster.Controllers
{
    public class MST_BranchController : Controller
    {
        private IConfiguration configuration;

        public MST_BranchController(IConfiguration _configuration)
        {
            this.configuration = _configuration;
        }
        public IActionResult MST_BranchList()
        {

            SqlConnection con = new SqlConnection(this.configuration.GetConnectionString("myConnectionString"));
            con.Open();
            SqlCommand cmd = con.CreateCommand();
            cmd.CommandType = System.Data.CommandType.StoredProcedure;
            cmd.CommandText = "SELECTALMST_Branch";
            DataTable dt = new DataTable();
            SqlDataReader dr = cmd.ExecuteReader();
            dt.Load(dr);
            con.Close();
            if (dt.Rows.Count == 0)
            {
                ViewBag.Branch = "NULL";
            }
            return View(dt);
        }

        public IActionResult MST_BranchAddEdit()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult MST_BranchAddEdit(MST_BranchModel branchModel)
        {

            if (ModelState.IsValid)
            {
                SqlConnection con = new SqlConnection(this.configuration.GetConnectionString("myConnectionString"));
                con.Open();
                SqlCommand sqlCommand = con.CreateCommand();
                sqlCommand.CommandType = System.Data.CommandType.StoredProcedure;
                if (branchModel.BranchID == null)
                {
                    sqlCommand.CommandText = "InsertMST_Branch";
                    TempData["message"] = "Record Inserted Successfully";
                }
                else
                {
                    sqlCommand.CommandText = "UPDATEMST_Branch";
                    sqlCommand.Parameters.AddWithValue("@ID", branchModel.BranchID);
                    TempData["message"] = "Record Updated Successfully";
                }
                sqlCommand.Parameters.AddWithValue("@BranchName", branchModel.BranchName);
                sqlCommand.Parameters.AddWithValue("@BranchCode", branchModel.BranchCode);
                sqlCommand.ExecuteNonQuery();
                return RedirectToAction("MST_BranchList");
            }
            else
            {
                return View("MST_BranchAddEdit");
            }
        }




        [HttpGet]
        public IActionResult MST_BranchEdit(int id)
        {
            SqlConnection con = new SqlConnection(this.configuration.GetConnectionString("myConnectionString"));
            con.Open();
            SqlCommand sqlCommand = con.CreateCommand();
            sqlCommand.CommandType = System.Data.CommandType.StoredProcedure;
            sqlCommand.CommandText = "SelectByPKMST_Branch";
            sqlCommand.Parameters.AddWithValue("@ID", id);
            DataTable dt = new DataTable();
            SqlDataReader sdr = sqlCommand.ExecuteReader();
            dt.Load(sdr);
            MST_BranchModel branchModel = new MST_BranchModel();
            if (dt.Rows.Count == 1)
            {
                foreach (DataRow dataRow in dt.Rows)
                {
                    branchModel.BranchID = Convert.ToInt32(dataRow[0]);
                    branchModel.BranchName = dataRow[1].ToString();
                    branchModel.BranchCode = dataRow[2].ToString();
                }
            }
            ViewBag.ID = id;
            con.Close();
            return View("MST_BranchAddEdit", branchModel);
        }

        public IActionResult MST_BranchDelete(int id)
        {
            try
            {
                SqlConnection con = new SqlConnection(this.configuration.GetConnectionString("myConnectionString"));
                con.Open();
                SqlCommand sqlCommand = con.CreateCommand();
                sqlCommand.CommandType = System.Data.CommandType.StoredProcedure;
                sqlCommand.CommandText = "DELETEMST_Branch";
                sqlCommand.Parameters.AddWithValue("@id", id);
                DataTable dt = new DataTable();
                sqlCommand.ExecuteNonQuery();
                TempData["message"] = "Record Deleted Successfully";
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                TempData["message"] = ex.Message;
            }
            return RedirectToAction("MST_BranchList");
        }
    }
}

Views/MST_Branch/MST_BranchAddEdit.cshtml
@model MST_BranchModel;

@{
    string opration = "";
    if (ViewBag.ID > 0)
    {
        opration = "Edit";
    }
    else
    {
        opration = "Add";
    }
}

<div class="row ">
<div class="col-lg-8 align-items-center">

    <div class="card">
        <div class="card-body">
            <h5 class="card-title">@opration Record</h5>
            <!-- Horizontal Form -->
                <form asp-action="MST_BranchAddEdit" asp-controller="MST_Branch" method="POST">
                    @Html.HiddenFor(x => x.BranchID)
                <div class="row mb-3">
                        <label class="col-sm-3 col-form-label">Branch Name</label>
                    <div class="col-sm-9">
                        <input asp-for="BranchName" type="text" class="form-control">
                        <span asp-validation-for="BranchName" class="text-danger"></span>
                    </div>
                </div>
                <div class="row mb-3">
                        <label class="col-sm-3 col-form-label">Branch Code</label>
                    <div class="col-sm-9">
                        <input type="text" asp-for="BranchCode" class="form-control">
                        <span asp-validation-for="BranchCode" class="text-danger"></span>
                    </div>
                </div>
                <div class="text-left">
                        <button type="submit" class="btn btn-primary">@opration Record</button>
                    </div>
                </form><!-- End Horizontal Form -->

            </div>
        </div>

    </div>
</div>

Views/MST_Branch/MST_BranchList.cshtml
@using System.Data;
@{
    string dateFormate(String input)
    {
        string[] ans = new string[3];
        ans = input.Split(' ');
        return ans[0];
    }
}

@if (TempData["message"] != null)
{
    if (TempData["message"].ToString().Contains("Successfully"))
    {
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <i class="bi bi-check-circle me-1"></i>
            @TempData["message"]
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    }
    else
    {
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <h4 class="alert-heading">Danger Heading</h4>
            <p>@TempData["message"]</p>
            <hr>
            <p class="mb-0">Somthing Went Wrong!</p>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    }

}
<div class="row">
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Branch Table</h5>
            <!-- Default Table -->
            @if (ViewBag.Branch != "NULL")
            {
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">ID</th>
                            <th scope="col">Branch Name</th>
                            <th scope="col">Branch Code</th>
                            <th scope="col">Created Date</th>
                            <th scope="col">Modified Date</th>
                            <th scope="col">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (DataRow data in Model.Rows)
                        {
                            <tr>
                                <th scope="row">@data["BranchID"]</th>
                                <td>@data["BranchName"]</td>
                                <td>@data["BranchCode"]</td>
                                <td>@dateFormate(data["Created"].ToString())</td>
                                <td>@dateFormate(data["Modified"].ToString())</td>
                                <td>
                                    <a asp-action="MST_BranchEdit" asp-controller="MST_Branch" asp-route-id="@data["BranchID"]" class="btn btn-primary btn-sm" title="Upload new profile image"><i class="bi bi-pencil-square"></i></a>
                                    <a asp-action="MST_BranchDelete" asp-controller="MST_Branch" asp-route-id="@data["BranchID"]" class="btn btn-danger btn-sm" title="Remove my profile image"><i class="bi bi-trash"></i></a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            }
            else
            {
                <h3>No Record Found</h3>
            }
            <!-- End Default Table Example -->
        </div>
    </div>
</div>