Controllers/LOC_CityController.cs
using Microsoft.AspNetCore.Mvc;
using StudentMaster.Models;
using System.Data.SqlClient;
using System.Data;

namespace StudentMaster.Controllers
{
    public class LOC_CityController : Controller
    {
        private IConfiguration configuration;
        public LOC_CityController(IConfiguration _configuration)
        {
            this.configuration = _configuration;
        }
        public IActionResult LOC_CityList()
        {
            SqlConnection conn = new SqlConnection(this.configuration.GetConnectionString("myConnectionString"));
            conn.Open();
            SqlCommand sqlCommand = conn.CreateCommand(); ;
            sqlCommand.CommandType = System.Data.CommandType.StoredProcedure;
            sqlCommand.CommandText = "SELECTALLOC_City";
            DataTable dt = new DataTable();
            SqlDataReader dr = sqlCommand.ExecuteReader();
            dt.Load(dr);
            if (dt.Rows.Count == 0)
            {
                ViewBag.City = "NULL";
            }
            return View(dt);
        }
        public void SetDropDownList()
        {
            SqlConnection conn = new SqlConnection(this.configuration.GetConnectionString("myConnectionString"));
            conn.Open();
            SqlCommand sqlCommand = conn.CreateCommand(); ;
            sqlCommand.CommandType = System.Data.CommandType.StoredProcedure;
            sqlCommand.CommandText = "LOC_StateList";
            DataTable dt = new DataTable();
            SqlDataReader dr = sqlCommand.ExecuteReader();
            dt.Load(dr);
            List<LOC_StateDropDownModel> stateDropDownModelList = new List<LOC_StateDropDownModel>();
            foreach (DataRow data in dt.Rows)
            {
                LOC_StateDropDownModel stateDropDownModel = new LOC_StateDropDownModel();
                stateDropDownModel.StateID = Convert.ToInt32(data["StateID"]);
                stateDropDownModel.StateCode = data["StateCode"].ToString();
                stateDropDownModelList.Add(stateDropDownModel);
            }
            ViewBag.stateDropDownModel = stateDropDownModelList;
            conn.Close();
        }
        public IActionResult LOC_CityAddEdit()
        {
            SetDropDownList();
            return View();

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult LOC_CityAddEdit(LOC_CityModel cityModel)
        {
            if (ModelState.IsValid)
            {
                SqlConnection conn = new SqlConnection(this.configuration.GetConnectionString("myConnectionString"));
                conn.Open();
                SqlCommand sqlCommand = conn.CreateCommand(); ;
                sqlCommand.CommandType = System.Data.CommandType.StoredProcedure;
                if (cityModel.CityID == null)
                {
                    sqlCommand.CommandText = "InsertLOC_City";
                    TempData["message"] = "Record Inserted Successfully";
                }
                else
                {
                    sqlCommand.CommandText = "UPDATELOC_City";
                    sqlCommand.Parameters.AddWithValue("@ID", cityModel.CityID);
                    TempData["message"] = "Record Updated Successfully";
                }
                sqlCommand.Parameters.AddWithValue("@StateID", cityModel.StateID);
                sqlCommand.Parameters.AddWithValue("@CityName", cityModel.CityName);
                sqlCommand.Parameters.AddWithValue("@CityCode", cityModel.CityCode);
                DataTable dt = new DataTable();
                SqlDataReader dr = sqlCommand.ExecuteReader();
                dt.Load(dr);
                return RedirectToAction("LOC_CityList");
            }
            else
            {
                SetDropDownList();
                return View();
            }
        }
        [HttpGet]
        public IActionResult LOC_CityEdit(int id)
        {
            SqlConnection con = new SqlConnection(this.configuration.GetConnectionString("myConnectionString"));
            con.Open();
            SqlCommand sqlCommand = con.CreateCommand();
            sqlCommand.CommandType = System.Data.CommandType.StoredProcedure;
            sqlCommand.CommandText = "SelectByPKLOC_City";
            sqlCommand.Parameters.AddWithValue("@ID", id);
            DataTable dt = new DataTable();
            SqlDataReader sdr = sqlCommand.ExecuteReader();
            dt.Load(sdr);
            LOC_CityModel cityModel = new LOC_CityModel();
            if (dt.Rows.Count == 1)
            {
                foreach (DataRow dataRow in dt.Rows)
                {
                    cityModel.CityID = Convert.ToInt32(dataRow[0]);
                    cityModel.StateID = Convert.ToInt32(dataRow[1]);
                    cityModel.CityName = dataRow[3].ToString();
                    cityModel.CityCode = dataRow[4].ToString();
                }
            }
            ViewBag.ID = id;
            con.Close();
            SetDropDownList();
            return View("LOC_CityAddEdit", cityModel);
        }
        public IActionResult LOC_CityDelete(int id)
        {

            try
            {
                SqlConnection con = new SqlConnection(this.configuration.GetConnectionString("myConnectionString"));
                con.Open();
                SqlCommand sqlCommand = con.CreateCommand();
                sqlCommand.CommandType = System.Data.CommandType.StoredProcedure;
                sqlCommand.CommandText = "DELETELOC_City";
                sqlCommand.Parameters.AddWithValue("@ID", id);
                DataTable dt = new DataTable();
                sqlCommand.ExecuteNonQuery();
                TempData["message"] = "Record Deleted Successfully";
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                TempData["message"] = ex.Message;
            }
            return RedirectToAction("LOC_CityList");
        }
    }
}

Views/LOC_City/LOC_CityAddEdit.cshtml
@using System.Data;
@model LOC_CityModel;


<div class="row ">
    <div class="col-lg-8 align-items-center">

        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Add City</h5>

                <!-- Multi Columns Form -->
                <form class="row g-3" asp-action="LOC_CityAddEdit" method="post">
                    @Html.HiddenFor(x => x.CityID)
                    <div class="col-md-12">
                        <label for="inputName5" class="form-label">City Name</label>
                        <input asp-for="CityName" type="text" class="form-control">
                        <span asp-validation-for="CityName" class="text-danger"></span>
                    </div>
                    <div class="col-md-6">
                        <label for="inputName5" class="form-label">City Code</label>
                        <input asp-for="CityCode" type="text" class="form-control">
                        <span asp-validation-for="CityCode" class="text-danger"></span>
                    </div>
                    <div class="col-md-6">
                        <label for="inputCity" class="form-label">State</label>
                        <select asp-for="StateID" asp-items="@(new SelectList(ViewBag.stateDropDownModel,"StateID","StateCode"))" id="inputCity" class="form-select">
                            <option>Select City---</option>
                        </select>
                        <span asp-validation-for="StateID" class="text-danger"></span>
                    </div>

                    <div class="text-left">
                        <button type="submit" class="btn btn-primary">Submit</button>

                    </div>
                </form><!-- End Multi Columns Form -->
            </div>
        </div>
    </div>
</div>

@*@section Scripts{
    @{
        <partial name = "_ValidationScriptsPartial" />
    }
}*@

Views/LOC_City/LOC_CityList.cshtml
@using System.Data;
@{
    string dateFormate(String input)
    {
        string[] ans = new string[3];
        ans = input.Split(' ');
        return ans[0];
    }
}

@if (TempData["message"] != null)
{
    if (TempData["message"].ToString().Contains("Successfully"))
    {
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <i class="bi bi-check-circle me-1"></i>
            @TempData["message"]
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    }
    else
    {
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <h4 class="alert-heading">Danger Heading</h4>
            <p>@TempData["message"]</p>
            <hr>
            <p class="mb-0">Somthing Went Wrong!</p>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    }

}
<div class="row">
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">City Table</h5>
            <!-- Default Table -->
            @if (ViewBag.City != "NULL")
            {
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">ID</th>
                            <th scope="col">City Name</th>
                            <th scope="col">City Code</th>
                            <th scope="col">State Code</th>
                            <th scope="col">Country Code</th>
                            <th scope="col">Created Date</th>
                            <th scope="col">Modified Date</th>
                            <th scope="col">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (DataRow data in Model.Rows)
                        {
                            <tr>
                                <th scope="row">@data["CityID"]</th>
                                <td>@data["CityName"]</td>
                                <td>@data["CityCode"]</td>
                                <td>@data["StateCode"]</td>
                                <td>@data["CountryCode"]</td>
                                <td>@dateFormate(data["CreationDate"].ToString())</td>
                                <td>@dateFormate(data["Modified"].ToString())</td>
                                <td>
                                    <a asp-action="LOC_CityEdit" asp-controller="LOC_City" asp-route-id="@data["CityID"]" class="btn btn-primary btn-sm" title="Upload new profile image"><i class="bi bi-pencil-square"></i></a>
                                    <a asp-action="LOC_CityDelete" asp-controller="LOC_City" asp-route-id="@data["CityID"]" class="btn btn-danger btn-sm" title="Remove my profile image"><i class="bi bi-trash"></i></a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            }
            else
            {
                <h3>No Record Found</h3>
            }
            <!-- End Default Table Example -->
        </div>
    </div>
</div>