Controllers/LOC_StateController.cs
using Microsoft.AspNetCore.Mvc;
using StudentMaster.Models;
using System.Data;
using System.Data.SqlClient;

namespace StudentMaster.Controllers
{
    public class LOC_StateController : Controller
    {
        private IConfiguration configuration;
        public LOC_StateController(IConfiguration _configuration)
        {
            this.configuration = _configuration;
        }
        public IActionResult LOC_StateList()
        {
            SqlConnection conn = new SqlConnection(this.configuration.GetConnectionString("myConnectionString"));
            conn.Open();
            SqlCommand sqlCommand = conn.CreateCommand(); ;
            sqlCommand.CommandType = System.Data.CommandType.StoredProcedure;
            sqlCommand.CommandText = "SELECTALLOC_State";
            DataTable dt = new DataTable();
            SqlDataReader dr = sqlCommand.ExecuteReader();
            dt.Load(dr);
            if (dt.Rows.Count == 0)
            {
                ViewBag.State = "NULL";
            }
            return View(dt);
        }
        public void SetDropDownList()
        {
            SqlConnection conn = new SqlConnection(this.configuration.GetConnectionString("myConnectionString"));
            conn.Open();
            SqlCommand sqlCommand = conn.CreateCommand(); ;
            sqlCommand.CommandType = System.Data.CommandType.StoredProcedure;
            sqlCommand.CommandText = "LOC_CountryList";
            DataTable dt = new DataTable();
            SqlDataReader dr = sqlCommand.ExecuteReader();
            dt.Load(dr);
            List<LOC_CountryDropDownModel> countryDropDownModelList = new List<LOC_CountryDropDownModel>();
            foreach (DataRow data in dt.Rows)
            {
                LOC_CountryDropDownModel countryDropDownModel = new LOC_CountryDropDownModel();
                countryDropDownModel.CountryID = Convert.ToInt32(data["CountryID"]);
                countryDropDownModel.CountryCode = data["CountryCode"].ToString();
                countryDropDownModelList.Add(countryDropDownModel);
            }

            ViewBag.countryDropDownModel = countryDropDownModelList;
            conn.Close();
        }
        public IActionResult LOC_StateAddEdit()
        {
            SetDropDownList();
            return View();

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult LOC_StateAddEdit(LOC_StateModel stateModel)
        {
            if (ModelState.IsValid)
            {
                SqlConnection conn = new SqlConnection(this.configuration.GetConnectionString("myConnectionString"));
                conn.Open();
                SqlCommand sqlCommand = conn.CreateCommand(); ;
                sqlCommand.CommandType = System.Data.CommandType.StoredProcedure;
                if (stateModel.StateID == null)
                {
                    sqlCommand.CommandText = "InsertLOC_State";
                    TempData["message"] = "Record Inserted Successfully";
                }
                else
                {
                    sqlCommand.CommandText = "UPDATELOC_State";
                    sqlCommand.Parameters.AddWithValue("@ID", stateModel.StateID);
                    TempData["message"] = "Record Updated Successfully";
                }
                sqlCommand.Parameters.AddWithValue("@CountryID", stateModel.CountryID);
                sqlCommand.Parameters.AddWithValue("@StateName", stateModel.StateName);
                sqlCommand.Parameters.AddWithValue("@StateCode", stateModel.StateCode);
                DataTable dt = new DataTable();
                SqlDataReader dr = sqlCommand.ExecuteReader();
                dt.Load(dr);
                return RedirectToAction("LOC_StateList");
            }
            else
            {
                SetDropDownList();
                return View();
            }
        }
        [HttpGet]
        public IActionResult LOC_StateEdit(int id)
        {
            SqlConnection con = new SqlConnection(this.configuration.GetConnectionString("myConnectionString"));
            con.Open();
            SqlCommand sqlCommand = con.CreateCommand();
            sqlCommand.CommandType = System.Data.CommandType.StoredProcedure;
            sqlCommand.CommandText = "SelectByPKLOC_State";
            sqlCommand.Parameters.AddWithValue("@ID", id);
            DataTable dt = new DataTable();
            SqlDataReader sdr = sqlCommand.ExecuteReader();
            dt.Load(sdr);
            LOC_StateModel stateModel = new LOC_StateModel();
            if (dt.Rows.Count == 1)
            {
                foreach (DataRow dataRow in dt.Rows)
                {
                    stateModel.StateID = Convert.ToInt32(dataRow[0]);
                    stateModel.CountryID = Convert.ToInt32(dataRow[1]);
                    stateModel.StateName = dataRow[2].ToString();
                    stateModel.StateCode = dataRow[3].ToString();
                }
            }
            ViewBag.ID = id;
            con.Close();
            SetDropDownList();
            return View("LOC_StateAddEdit", stateModel);
        }
        public IActionResult LOC_StateDelete(int id)
        {
            SqlConnection con = new SqlConnection(this.configuration.GetConnectionString("myConnectionString"));
            con.Open();
            SqlCommand sqlCommand = con.CreateCommand();
            sqlCommand.CommandType = System.Data.CommandType.StoredProcedure;
            sqlCommand.CommandText = "DELETELOC_State";
            sqlCommand.Parameters.AddWithValue("@ID", id);
            DataTable dt = new DataTable();
            sqlCommand.ExecuteNonQuery();
            TempData["message"] = "Record Deleted Successfully";
            return RedirectToAction("LOC_StateList");
        }
    }
}

Views/LOC_State/LOC_StateAddEdit.cshtml
@using System.Data;
@model LOC_StateModel;


<div class="row ">
    <div class="col-lg-8 align-items-center">

<div class="card">
    <div class="card-body">
        <h5 class="card-title">Add State</h5>

        <!-- Multi Columns Form -->
        <form class="row g-3" asp-action="LOC_StateAddEdit" method="post">
                    @Html.HiddenFor(x => x.StateID)
            <div class="col-md-12">
                <label for="inputName5" class="form-label">State Name</label>
                <input asp-for="StateName"  type="text" class="form-control">
                <span asp-validation-for = "StateName" class="text-danger"></span>
            </div>
            <div class="col-md-6">
                 <label for="inputName5" class="form-label">State Code</label>
                 <input asp-for="StateCode" type="text" class="form-control">
                 <span asp-validation-for="StateCode" class="text-danger"></span>
            </div>
            <div class="col-md-6">
                        <label for="inputState" class="form-label">Country</label>
                        <select asp-for="CountryID" asp-items="@(new SelectList(ViewBag.countryDropDownModel,"CountryID","CountryCode"))" id="inputState" class="form-select">
                            <option>Select State---</option>
                        </select>
                        <span asp-validation-for="CountryID" class="text-danger"></span>   
            </div>

            <div class="text-left">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </form><!-- End Multi Columns Form -->
    </div>
</div>
</div>
</div>

@*@section Scripts{
    @{
        <partial name = "_ValidationScriptsPartial" />
    }
}*@

Views/LOC_State/LOC_StateList.cshtml
@using System.Data;
@{
    string dateFormate(String input)
    {
        string[] ans = new string[3];
        ans = input.Split(' ');
        return ans[0];
    }
}

@if (TempData["message"] != null)
{
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <i class="bi bi-check-circle me-1"></i>
        @TempData["message"]
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>

}
<div class="row">
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">State Table</h5>
            <!-- Default Table -->
            @if(ViewBag.State != "NULL")
            {
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">ID</th>
                            <th scope="col">State Name</th>
                            <th scope="col">State Code</th>
                            <th scope="col">Country Code</th>
                            <th scope="col">Created Date</th>
                            <th scope="col">Modified Date</th>
                            <th scope="col">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (DataRow data in Model.Rows)
                        {
                            <tr>
                                <th scope="row">@data["StateID"]</th>
                                <td>@data["StateName"]</td>
                                <td>@data["StateCode"]</td>
                                <td>@data["CountryCode"]</td>
                                <td>@dateFormate(data["Created"].ToString())</td>
                                <td>@dateFormate(data["Modified"].ToString())</td>
                                <td>
                                    <a asp-action="LOC_StateEdit" asp-controller="LOC_State" asp-route-id="@data["StateID"]" class="btn btn-primary btn-sm" title="Upload new profile image"><i class="bi bi-pencil-square"></i></a>
                                    <a asp-action="LOC_StateDelete" asp-controller="LOC_State" asp-route-id="@data["StateID"]" class="btn btn-danger btn-sm" title="Remove my profile image"><i class="bi bi-trash"></i></a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            }
            else
            {
                <h3>No Record Found</h3>
            }
            <!-- End Default Table Example -->
        </div>
    </div>
</div>