Controllers/MST_StudentController.cs
using Microsoft.AspNetCore.Mvc;
using System.Data.SqlClient;
using System.Data;
using StudentMaster.Models;
using Microsoft.AspNetCore.Mvc.DataAnnotations;

namespace StudentMaster.Controllers
{
    public class MST_StudentController : Controller
    {
        private IConfiguration configuration;

        public MST_StudentController(IConfiguration _configuration)
        {
            this.configuration = _configuration;
        }
        public IActionResult MST_StudentList()
        {

            SqlConnection con = new SqlConnection(this.configuration.GetConnectionString("myConnectionString"));
            con.Open();
            SqlCommand cmd = con.CreateCommand();
            cmd.CommandType = System.Data.CommandType.StoredProcedure;
            cmd.CommandText = "SELECTALMST_Student";
            DataTable dt = new DataTable();
            SqlDataReader dr = cmd.ExecuteReader();
            dt.Load(dr);
            con.Close();
            if (dt.Rows.Count == 0)
            {
                ViewBag.Student = "NULL";
            }
            return View(dt);
        }
        public IActionResult MST_StudentAddEdit()
        {
            SetBranchDropDownList();
            SetCityDropDownList();
            return View();
        }

        string dateFormate(String input)
        {
            string[] ans = new string[3];
            ans = input.Split(' ');
            return ans[0];
        }

        #region Student Add | Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult MST_StudentAddEdit(MST_StudentModel studentModel)
        {

            if (ModelState.IsValid)
            {
                SqlConnection con = new SqlConnection(this.configuration.GetConnectionString("myConnectionString"));
                con.Open();
                SqlCommand sqlCommand = con.CreateCommand();
                sqlCommand.CommandType = System.Data.CommandType.StoredProcedure;
                if (studentModel.StudentID == null)
                {
                    sqlCommand.CommandText = "InsertMST_Student";
                    sqlCommand.Parameters.AddWithValue("@Password", studentModel.Password);
                    TempData["message"] = "Record Inserted Successfully";
                }
                else
                {
                    sqlCommand.CommandText = "UPDATEMST_Student";
                    sqlCommand.Parameters.AddWithValue("@ID", studentModel.StudentID);
                    TempData["message"] = "Record Updated Successfully";
                }

                #region Add Parameteres

                sqlCommand.Parameters.AddWithValue("@BranchID", studentModel.BranchID);
                sqlCommand.Parameters.AddWithValue("@CityID", studentModel.CityID);
                sqlCommand.Parameters.AddWithValue("@StudentName", studentModel.StudentName);
                sqlCommand.Parameters.AddWithValue("@MobileNoStudent", studentModel.MobileNoStudent);
                sqlCommand.Parameters.AddWithValue("@Email", studentModel.Email);
                sqlCommand.Parameters.AddWithValue("@MobileNoFather", studentModel.MobileNoFather);
                sqlCommand.Parameters.AddWithValue("@Address", studentModel.Address);
                sqlCommand.Parameters.AddWithValue("@BirthDate", dateFormate(studentModel.BirthDate.ToString())); 
                #endregion


                if (studentModel.IsActive == "Yes")
                {
                    sqlCommand.Parameters.AddWithValue("@IsActive", 1);
                }
                else
                {
                    sqlCommand.Parameters.AddWithValue("@IsActive", 0);
                }
                sqlCommand.Parameters.AddWithValue("@Gender", studentModel.Gender);

                sqlCommand.ExecuteNonQuery();
                if (studentModel.StudentID == null)
                {
                    return RedirectToAction("MST_StudentList");
                }
                else
                {
                    return RedirectToAction("MST_StudentProfile", new { id = studentModel.StudentID });
                }
            }
            else
            {
                SetBranchDropDownList();
                SetCityDropDownList();
                return View("MST_StudentAddEdit");
            }
        }
        #endregion

        #region Fill City Dropdown
        public void SetCityDropDownList()
        {
            SqlConnection conn = new SqlConnection(this.configuration.GetConnectionString("myConnectionString"));
            conn.Open();
            SqlCommand sqlCommand = conn.CreateCommand(); ;
            sqlCommand.CommandType = System.Data.CommandType.StoredProcedure;
            sqlCommand.CommandText = "LOC_CityList";
            DataTable dt = new DataTable();
            SqlDataReader dr = sqlCommand.ExecuteReader();
            dt.Load(dr);
            List<LOC_CityDropDown> cityDropDownModelList = new List<LOC_CityDropDown>();
            foreach (DataRow data in dt.Rows)
            {
                LOC_CityDropDown cityDropDownModel = new LOC_CityDropDown();
                cityDropDownModel.CityID = Convert.ToInt32(data["CityID"]);
                cityDropDownModel.CityCode = data["CityCode"].ToString();
                cityDropDownModelList.Add(cityDropDownModel);
            }

            ViewBag.cityDropDownModel = cityDropDownModelList;
            conn.Close();
        }

        #endregion

        #region Fill State Dropdown
        public void SetBranchDropDownList()
        {
            SqlConnection conn = new SqlConnection(this.configuration.GetConnectionString("myConnectionString"));
            conn.Open();
            SqlCommand sqlCommand = conn.CreateCommand(); ;
            sqlCommand.CommandType = System.Data.CommandType.StoredProcedure;
            sqlCommand.CommandText = "MST_BranchList";
            DataTable dt = new DataTable();
            SqlDataReader dr = sqlCommand.ExecuteReader();
            dt.Load(dr);
            List<LOC_BranchDropDownModel> branchDropDownModelList = new List<LOC_BranchDropDownModel>();
            foreach (DataRow data in dt.Rows)
            {
                LOC_BranchDropDownModel branchDropDownModel = new LOC_BranchDropDownModel();
                branchDropDownModel.BranchID = Convert.ToInt32(data["BranchID"]);
                branchDropDownModel.BranchCode = data["BranchCode"].ToString();
                branchDropDownModelList.Add(branchDropDownModel);
            }

            ViewBag.branchDropDownModel = branchDropDownModelList;
            conn.Close();
        } 
        #endregion

        public IActionResult MST_StudentProfile(int id)
        {
            SetBranchDropDownList();
            SetCityDropDownList();
            SqlConnection con = new SqlConnection(this.configuration.GetConnectionString("myConnectionString"));
            con.Open();
            SqlCommand sqlCommand = con.CreateCommand();
            sqlCommand.CommandType = System.Data.CommandType.StoredProcedure;
            sqlCommand.CommandText = "SelectByPKMST_Student";
            sqlCommand.Parameters.AddWithValue("@ID", id);
            DataTable dt = new DataTable();
            SqlDataReader sdr = sqlCommand.ExecuteReader();
            dt.Load(sdr);
            MST_StudentModel studentModel = new MST_StudentModel();
            if (dt.Rows.Count == 1)
            {
                foreach (DataRow dataRow in dt.Rows)
                {
                    studentModel.StudentID = Convert.ToInt32(dataRow[0]);
                    studentModel.BranchID = Convert.ToInt32(dataRow[1]);
                    studentModel.CityID = Convert.ToInt32(dataRow[2]);
                    studentModel.StudentName = dataRow[3].ToString();
                    studentModel.MobileNoStudent = dataRow[4].ToString();
                    studentModel.Email = dataRow[5].ToString();
                    studentModel.MobileNoFather = dataRow[6].ToString();
                    studentModel.Address = dataRow[7].ToString();
                    studentModel.BirthDate = Convert.ToDateTime(dataRow[8].ToString());
                    studentModel.Age = Convert.ToInt32(dataRow[9].ToString());
                    studentModel.IsActive = dataRow[10].ToString();
                    studentModel.Gender = dataRow[11].ToString();
                    studentModel.Password = dataRow[12].ToString();
                    studentModel.Created = dataRow[13].ToString();
                    studentModel.Modified = dataRow[14].ToString();
                    ViewBag.BranchName = dataRow[15].ToString();
                    ViewBag.CityName = dataRow[16].ToString();
                }
            }
            ViewBag.ID = id;
            con.Close();
            return View(studentModel);
            
        }
        public IActionResult MST_StudentDelete(int id)
        {

            try
            {
                SqlConnection con = new SqlConnection(this.configuration.GetConnectionString("myConnectionString"));
                con.Open();
                SqlCommand sqlCommand = con.CreateCommand();
                sqlCommand.CommandType = System.Data.CommandType.StoredProcedure;
                sqlCommand.CommandText = "DELETEMST_Student";
                sqlCommand.Parameters.AddWithValue("@ID", id);
                DataTable dt = new DataTable();
                sqlCommand.ExecuteNonQuery();
                TempData["message"] = "Record Deleted Successfully";
            }
            catch (Exception ex)
            {
                TempData["message"] = ex.Message;
            }
            return RedirectToAction("MST_StudentList");
        }
        public IActionResult SearchStudentName(string studentName)
        {
            ViewBag.Student = studentName;
                if (studentName == null)
            {
                return RedirectToAction("MST_StudentList");
            }

Views/MST_Student/MST_StudentAddEdit.cshtml
@using System.Data;
@model MST_StudentModel;


<div class="row ">
    <div class="col-lg-8 align-items-center">

        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Multi Columns Form</h5>
                <!-- Multi Columns Form -->
                <form class="row g-3" asp-action="MST_StudentAddEdit" method="post">
                    @Html.HiddenFor(x => x.StudentID)
                    <div class="col-md-12">
                        <label for="inputName5" class="form-label">Your Name</label>
                        <input asp-for="StudentName" type="text" class="form-control" id="inputName5">
                        <span asp-validation-for="StudentName" class="text-danger"></span>
                    </div>
                    <div class="col-md-6">
                        <label for="inputEmail5" class="form-label">Email</label>
                        <input asp-for="Email" type="email" class="form-control" id="inputEmail5">
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>

                    <div class="col-md-6">
 
                        <label for="inputPassword5" class="form-label">Password</label>
                        <input asp-for="Password"  type="password" class="form-control" id="inputPassword5">
                        <span asp-validation-for="Password" class="text-danger"></span>
                        
                    </div>
                    <div class="col-12">
                        <label for="inputAddress5" class="form-label">Address</label>
                        <textarea asp-for="Address"  type="text" class="form-control" id="inputAddres5s"></textarea>
                        <span asp-validation-for="Address" class="text-danger"></span>
                    </div>
                    <div class="col-md-4">
                        <label for="inputZip" class="form-label">Gender</label>
                        <select asp-for="Gender" id="inputState" class="form-select">
                            <option selected="">Choose...</option>
                            <option>Male</option>
                            <option>Female</option>
                        </select>
                        <span asp-validation-for="Gender" class="text-danger"></span>
                    </div>
                    <div class="col-md-4">
                        <label for="inputState" class="form-label">Branch</label>
                        <select asp-for="BranchID" asp-items="@(new SelectList(ViewBag.branchDropDownModel,"BranchID","BranchCode"))" id="inputState" class="form-select">
                            <option selected="">Choose...</option>
                        </select>
                        <span asp-validation-for="BranchID" class="text-danger"></span>
                    </div>
                    <div class="col-md-4">
                        <label for="inputZip" class="form-label">City</label>
                        <select asp-for="CityID" asp-items="@(new SelectList(ViewBag.cityDropDownModel,"CityID","CityCode"))" id="inputState" class="form-select">
                            <option selected="">Choose...</option>
                        </select>
                        <span asp-validation-for="CityID" class="text-danger"></span>
                    </div>
                    <div class="col-md-6">
                        <label for="inputEmail5" class="form-label">Student Mobile No.</label>
                        <input asp-for="MobileNoStudent" type="text" class="form-control" id="inputEmail5">
                        <span asp-validation-for="MobileNoStudent" class="text-danger"></span>
                    </div>

                    <div class="col-md-6">

                        <label for="inputPassword5" class="form-label">Father Mobile No.</label>
                        <input asp-for="MobileNoFather" type="text" class="form-control" id="inputPassword5">
                        <span asp-validation-for="MobileNoFather" class="text-danger"></span>

                    </div>
                    <div class="col-md-4">
                        <label for="inputDate5" class="form-label" >Birth Date</label>
                        <input asp-for="BirthDate" type="date" class="form-control" id="inputDate5" onchange="fun()">
                        <span asp-validation-for="BirthDate" class="text-danger"></span>
                    </div>
                    <div class="col-md-4">
                        <label for="inputZip" class="form-label">IsActivy</label>
                        <select asp-for="IsActive" id="inputState" class="form-select">
                            <option selected="">Yes</option>
                            <option>No</option>
                        </select>
                        <span asp-validation-for="IsActive" class="text-danger"></span>
                    </div>
                    <div class="col-md-4">
                        <label for="inputDate5" class="form-label">Age</label>
                        <input type="text" class="form-control" id="inputDate6"  disabled="">
                    </div>
                    <div class="text-left">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form><!-- End Multi Columns Form -->

            </div>
        </div>
    </div>
</div>


<script>
    function fun(){
        
        var dob = document.getElementById('inputDate5').value;
        const date = new Date();
        let year = date.getFullYear();
        document.getElementById("inputDate6").setAttribute('value', year - (dob.split('-')[0]));
    }
</script>
@*@section Scripts{
    @{
        <partial name = "_ValidationScriptsPartial" />
    }
}*@

Views/MST_Student/MST_StudentList.cshtml
@using System.Data;
@{
    MST_StudentModel studentModel = new MST_StudentModel();
}
@{
    string dateFormate(String input)
    {
        string[] ans = new string[3];
        ans = input.Split(' ');
        return ans[0];
    }
}
@if (TempData["message"] != null)
{
    if (TempData["message"].ToString().Contains("Successfully"))
    {
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <i class="bi bi-check-circle me-1"></i>
            @TempData["message"]
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    }
    else
    {
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <h4 class="alert-heading">Danger Heading</h4>
            <p>@TempData["message"]</p>
            <hr>
            <p class="mb-0">Somthing Went Wrong!</p>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    }

}
<style>
   .search-form input {
        border: 0;
        font-size: 14px;
        color: #012970;
        border: 1px solid rgba(1, 41, 112, 0.2);
        padding: 7px 38px 7px 8px;
        border-radius: 3px;
        transition: 0.3s;
        width: 100%;
   }
    .search-form button{
        border: 0;
        padding: 0;
        margin-left: -30px;
        background: none;
    }
</style>
<div class="row">
    <div class="search-bar col-md-4 mb-3">
        <form class="search-form d-flex align-items-center" asp-action="SearchStudentName">
            <input type="text" name="studentName" placeholder="Student Name" title="Enter search keyword" id="txtSearch">
            <button type="submit" title="Search" fdprocessedid="mgo3f"><i  class="bi bi-search"></i></button>
        </form>
        
    </div><!-- End Search Bar -->

</div>
<div class="row">
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Student Table</h5>
            <!-- Default Table -->
            @if (ViewBag.Student != "NULL")
            {
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">ID</th>
                            <th scope="col">Student Name</th>
                            <th scope="col">Branch Code</th>
                            <th scope="col">City Code</th>
                            <th scope="col">Created Date</th>
                            <th scope="col">Modified Date</th>
                            <th scope="col">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (DataRow data in Model.Rows)
                        {
                            <tr>
                                <th scope="row">@data["StudentID"]</th>
                                <td>@data["StudentName"]</td>
                                <td>@data["BranchCode"]</td>
                                <td>@data["CityCode"]</td>
                                <td>@dateFormate(data["Created"].ToString())</td>
                                <td>@dateFormate(data["Modified"].ToString())</td>
                                <td>
                                    <a asp-action="MST_StudentProfile" asp-controller="MST_Student" asp-route-id="@data["StudentID"]" class="btn btn-primary btn-sm" title="Upload new profile image"><i class="bi bi-person-lines-fill"></i></a>
                                    <a asp-action="MST_StudentDelete" asp-controller="MST_Student" asp-route-id="@data["StudentID"]" class="btn btn-danger btn-sm" title="Remove my profile image"><i class="bi bi-trash"></i></a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            }
            else
            {
                <h3>No Record Found</h3>
            }
            <!-- End Default Table Example -->
        </div>
    </div>
</div>


@section Scripts{
    <script>
        $(document).ready(function () {
            var studentName = '@ViewBag.Student';
            $("#txtSearch").val(studentName);
        });
    </script>
}